name: Checkmarx SCA Scan (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sca-scan:
    name: Download and Extract CxSCA Resolver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download and extract CxSCA Resolver (Linux)
        run: |
          curl -L -o ScaResolver-linux64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzf ScaResolver-linux64.tar.gz
          chmod 755 ./ScaResolver  # Ensure proper permissions
          ls -l ./ScaResolver  # Verify permissions
          ./ScaResolver --help  # Test executable

      - name: Upload CxSCA Resolver as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScaResolver
          path: ./ScaResolver

  ast-scan:
    name: Run Checkmarx AST Scan
    runs-on: ubuntu-latest
    needs: sca-scan

    steps:

      - name: Download CxSCA Resolver artifact
        uses: actions/download-artifact@v4
        with:
          name: ScaResolver

      - name: Verify ScaResolver location and permissions
        run: |
          ls -l /github/workspace  # List contents of /github/workspace
          ls -l /github/workspace/ScaResolver  # Verify that ScaResolver is here
          file /github/workspace/ScaResolver  # Verify it's a valid executable

      - name: Ensure permissions inside Docker container
        run: |
          sudo chmod 755 /github/workspace/ScaResolver  # Ensure executable permissions inside Docker container
          ls -l /github/workspace/ScaResolver  # Verify the file is executable inside Docker

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://eu.ast.checkmarx.net
          cx_tenant: ast_abdul_ansari
          cx_client_id: dhruv-lts-1
          cx_client_secret: a7JMTAwqqu56bHgS9JLmqWrw7jqdshf5
          additional_params: '--sca-resolver /github/workspace/ScaResolver' 
